from core.settings import env

SLEEP_TIME = env("SLEEP_TIME")

COUNTRIES_API = env("COUNTRIES_API")

CITIES_API = env("CITIES_API")
CITY_MIN_POPULATION = env("CITY_MIN_POPULATION")
CITY_ORDER = env("CITY_ORDER")
CITY_TYPES = env("CITY_TYPES")
CITY_LIMIT = env("CITY_LIMIT")
CITY_API_KEY = env("CITY_API_KEY")
CITY_API_KEY_VALUE = env("CITY_API_KEY_VALUE")
CITY_API_HOST_KEY = env("CITY_API_HOST_KEY")
CITY_API_HOST_VALUE = env("CITY_API_HOST_VALUE")
REGION_API = env("REGION_API")

CURRENCY_API = env("CURRENCY_API")
CURRENCY_API_KEY = env("CURRENCY_API_KEY")
CURRENCY_API_TOKEN = env("CURRENCY_API_TOKEN")

WEATHER_API_KEY = env("WEATHER_API_KEY")
WEATHER_API_TOKEN = env("WEATHER_API_TOKEN")
WEATHER_API_URL = env("WEATHER_API_URL")
