# Generated by Django 4.1 on 2023-09-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_latitude_city_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(max_length=32, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(max_length=32, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='utc',
            field=models.CharField(max_length=64, unique=True, verbose_name='UTC'),
        ),
    ]
