# Generated by Django 4.1 on 2023-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_city_latitude_alter_city_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код города'),
        ),
        migrations.AddField(
            model_name='city',
            name='utc',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='UTC'),
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
    ]
